name: Quality assurance worflow
on:
  pull_request:
    branches: 
    - master
    - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Running Automated tests

    steps: 
      - run: ls -a