name: Quality assurance worflow
on:
  pull_request:
    branches: 
    - master
    - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Running Automated tests

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: yarn coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/coverage-summary.json
      - uses: rodrigo-md/pull-request-visualizer-action/packages/coverage-report@testing-action
        with:
          use-coverage-report: true
          coverage-artifact-name: coverage-report
          coverage-artifact-path: coverage/coverage-summary.json
      - run: git branch -a
      - id: git-diff
        uses: rodrigo-md/pull-request-visualizer-action/packages/git-diff@testing-action
        with:
          source-branch: ${{ github.head_ref }}
          target-branch: ${{ github.base_ref }}
      - run: echo ${{steps.git-diff.outputs.diff-summary}}
