name: Quality assurance worflow
on:
  pull_request:
    branches: 
    - master
    - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Running Automated tests

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: yarn coverage
